name: vegmapper
channels:
  - conda-forge
dependencies:
#all modules
  - pandas
  - geopandas
  - scipy
  - numpy
  - gdal
  - ipython
  - nodejs
  - ipywidgets
  - jupyterlab
  - rasterio
  - kernda
  - opencv
  - wget
  - requests
  - pip
  - python=3.9
  - s3fs
# stacks
  - asf_search
  - backoff
  - boto3
  - gdal
  - gsutil
  - h5py
  - hyp3_sdk
  - xarray
  - rioxarray
#calval modules
  - ee
  - geemap
  - functools
  - pdb
  - pylab
  - earthengine-api
#classification modules
#  - pip:
#   - appdirs
#    - asciitree
#    - cftime
#    - cloudpickle
#    - cmake
#    - configobj
#    - cuda-python
#   - tqdm --index-url https://download.pytorch.org/whl/cu118
#   - torch --index-url https://download.pytorch.org/whl/cu118
#    - torchvision  --index-url https://download.pytorch.org/whl/cu118
#    - --extra-index-url https://pypi.nvidia.com
#   - cuml-cu11
#   - cupy-cuda11x
#    - cython
#    - dask
#    - dask-cuda
#    - dask-glm
#    - dask-ml
#    - diplib
#   - distributed
#    - fastrlock
#    - filelock
#    - fsspec
#    - geocube
#    - gputil
#    - imageio
#   - lazy-loader
#   - lit
#    - llvmlite
#   - locket
#   - mpmath
#    - msgpack
#    - multipledispatch
#    - netcdf4
#    - numba
#    - numcodecs
#    - numpy
#    - nvtx
#    - odc-geo
#    - pandas
#    - partd
#    - pyarrow
#    - pykdtree
#    - pynvml
#    - pykdtree
#    - pynvml
#    - pyresample
#    - pywavelets
#    - rioxarray
#   - scikit-image
#   - scikit-learn
#   - sortedcontainers
#    - sympy
#    - tblib
#    - tifffile
#    - toolz
#    - treelite
#    - treelite-runtime
#    - triton
#    - xarray
#    - zarr
#    - zict



