# To use:
#
#   $ conda env create -f environment.yml
#   $ conda activate vegmapper
#
name: vegmapper
channels:
  - conda-forge
dependencies:
  - asf_search
  - boto3
  - earthengine-api
  - gdal
  - geopandas
  - gsutil
  - h5py
  - hyp3_sdk
  - jupyterlab
  - numpy
  - opencv
  - pandas
  - python=3.9
  - rasterio
  - requests
  - s3fs
